#!/bin/bash
read -p "Voulez-vous vérifier ce commit (y/[n]) ?" yn < /dev/tty
yn=${yn:-n}
case $yn in
    [Yy]* )
        mkdir -p suivi
        echo "commit vérifié le $(date)" > suivi/commitInfo.txt
        git add suivi/commitInfo.txt
        exit 0;;
    [Nn]* )
        exit 0;;
esac
exit 0